# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\zinez\OneDrive\Documents\BSU schoolwork\BSU Year 5\Comp 490 Senior Dev\Projects\tzineIMDBProject\DBUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(752, 510)
        self.rank = QtWidgets.QDialogButtonBox(Dialog)
        self.rank.setGeometry(QtCore.QRect(570, 470, 171, 31))
        self.rank.setOrientation(QtCore.Qt.Horizontal)
        self.rank.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.rank.setObjectName("rank")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 751, 471))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)

        self.retranslateUi(Dialog)
        self.rank.accepted.connect(Dialog.accept)
        self.rank.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "rank"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "rank_up_down"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "title"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "full_title"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "year"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "crew"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "imdb_rating"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "imdb_rating_count"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
